name: DSPRE Beta Canary Build

on:
  push:
    branches:
      - main  # Trigger only on pushes to the main branch

permissions:
  contents: write

env:
  SOLUTION_FILE_PATH: DS_Map.sln
  BUILD_CONFIGURATION: Release

jobs:
  build:
    if: github.repository == 'Mixone-FInallyHere/DS-Pokemon-Rom-Editor'
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build DSPRE
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}
    
    - name: Zip Release Files
      run: Compress-Archive -Path ${{env.GITHUB_WORKSPACE}}DS_Map\bin\Release -DestinationPath DSPRE-beta-canary.zip

    - name: Fetch tags
      run: git fetch --prune --unshallow --tags

    - name: Get current timestamp
      id: timestamp
      run: echo "::set-output name=ts::$(date +'%Y%m%d-%H%M%S')"

    - name: Create tag for current build
      run: |
       git config user.name "github-actions[bot]"
       git config user.email "github-actions[bot]@users.noreply.github.com"
       git tag beta_canary-${{ steps.timestamp.outputs.ts }}
       git push origin beta_canary-${{ steps.timestamp.outputs.ts }}

    - name: Delete previous release
      run: |
        gh release delete --yes beta_canary

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
        
    - name: Create new release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: beta_canary-${{ steps.timestamp.outputs.ts }}
        name: DSPRE Beta Canary Build ${{ steps.date.outputs.date }}
        files: DSPRE-beta-canary.zip
        token: ${{ secrets.GITHUB_TOKEN }}
        body: |
          ##  ‚ö†Ô∏è Canary Build Notice ‚ö†Ô∏è
          This is a Canary Build of DSPRE Beta, meaning it is automatically generated from the latest pushed code. It includes the most recent changes, improvements, and experimental features, but may be unstable or contain bugs.
          
          ## üöß What does this mean?
          This build reflects ongoing development and is not a stable release.
          Features may be incomplete, subject to change, or cause unexpected issues.
          Use at your own risk‚Äîexpect potential crashes, broken functionality, or unpolished features.
          
          ## üí° Who is this for?
          Developers and testers who want to stay up-to-date with the latest progress.
          Users willing to report issues and provide feedback on new changes.
          If you‚Äôre looking for a more reliable version, consider using the latest Stable Release instead.
        prerelease: true
        generate_release_notes: true
